apiVersion: v1
kind: Service
metadata:
  name: idziemy-app-service
  labels:
    app: idziemy-app
spec:
  type: LoadBalancer # Use NodePort or ClusterIP if you don't need an external IP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: idziemy-app